FROM php:8.1-fpm-alpine
# php 8.1
# fpm server
# AlpineLinux ver11 * 軽量化の為Alpine採用、本番環境では公式イメージの利用を推奨

WORKDIR /var/www/html

ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_HOME=/composer

# install composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

# install packages
RUN apk update
RUN apk add git

# install php extensions
RUN docker-php-ext-install pdo pdo_mysql
# copy soruce
# COPY . .
