version: '3.9'
# https://sagara.ink/article/app/204/
# https://qiita.com/ucan-lab/items/56c9dc3cf2e6762672f4

services:
  proxy:
    container_name: example-proxy
    build: ./nginx
    ports: 
      - 8080:80
    volumes:
      - ./backend:/usr/share/nginx/html  # 動作確認用
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  backend:
    container_name: example-be
    build: ./backend
    restart: always
    volumes:
      - ./backend:/var/www/html
      - ./backend/php.ini:/usr/local/php/php.ini
    depends_on:
      - db
  
  frontend:
    container_name: example-fe
    build: ./frontend
    stdin_open: true
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app

  db:
    container_name: example-db
    build: ./mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - example-db-volume:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: example_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo

  phpmyadmin:
    container_name: example-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ROOT_PASSWORD=rootpassword

volumes:
  example-db-volume:
